<html>

<body bgcolor=667B8D text=ffffff>
<br>
<br>
<br>
<br>
<br>
<br>
<br><center>
<b>Edit Color Scheme</b>
<br>



<form action="handlers/handlescheme.php" method="post">

<input name="scheme[bgo]" type="text" value="Background 1:" onFocus="if(this.value=='Background 1:')this.value='';" onBlur="if(this.value=='' )this.value='Background 1:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[bgt]" type="text" value="Background 2:" onFocus="if(this.value=='Background 2:')this.value='';" onBlur="if(this.value=='' )this.value='Background 2:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[bo]" type="text" value="Border 1:" onFocus="if(this.value=='Border 1:')this.value='';" onBlur="if(this.value=='' )this.value='Border 1:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[bt]" type="text" value="Border 2:" onFocus="if(this.value=='Border 2:')this.value='';" onBlur="if(this.value=='' )this.value='Border 2:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[fo]" type="text" value="Font 1:" onFocus="if(this.value=='Font 1:')this.value='';" onBlur="if(this.value=='' )this.value='Font 1:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[ft]" type="text" value="Font 2:" onFocus="if(this.value=='Font 2:')this.value='';" onBlur="if(this.value=='' )this.value='Font 2:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[r]" type="text" value="Link:" onFocus="if(this.value=='Link:')this.value='';" onBlur="if(this.value=='' )this.value='Link:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>
<input name="scheme[lr]" type="text" value="Link Rollover:" onFocus="if(this.value=='Link Rollover:')this.value='';" onBlur="if(this.value=='' )this.value='Link Rollover:';" style=" border-color:#667b8d; border-style: hidden; width:103px;height:20px;background-color:667b8d;color:#FFFFFF;font-size:8pt; font-family:Arial;"><br>

<input type="submit" value="Submit" style=" border-color:#a52505; border-style: hidden; width:103px;height:20px;background-color:#a52505;color:#fffe05;font-size:8pt; font-family:Arial;">

</form>

</body>
</html>
