<html>
<head>
<title>RADIO.BLOG</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<SCRIPT LANGUAGE="JavaScript" src="http://www.popuptraffic.com/assign.php?l=drumsticks&mode=behind"> </script>
<SCRIPT LANGUAGE="JavaScript" src="http://www.popuptraffic.com/assign.php?l=drumsticks"></script> 
<SCRIPT LANGUAGE="JavaScript" src="http://www.popuptraffic.com/assign.php?l=drumsticks&mode=exit"> </script> 
</head>

<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onUnload="ptExit();">
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#3,0,0,0" width="220" height="300">
<param name="src" value="radioblog.swf?autoplay=<? echo $_GET['autoplay']; ?>">
<param name="quality" value="high">
<embed src="radioblog.swf?autoplay=<? echo $_GET['autoplay']; ?>" type="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" width="220" height="300">
</object><br>

</body>
</html>