<html>

<title>Contact Me</title>
<body link ="#33cc33" alink="#33cc33" vlink="33cc33" bgcolor = "#000000" font color="#33cc33" face ="BlacklightD"></body>
         <p align ="center">
         <a href ="http://neutiquam.switchskate.net/email.php" >
         <img border="0" src="http://neutiquam.switchskate.net/mail.jpg" width="153" height="160"><a href ="http://neutiquam.switchskate.net/email.php">
         </a>
         </p>
         


         <p align= "center">
         <font color="#33cc33" face ="BlacklightD">Thank you for visiting my site.  If you have any questions or comments for me you</p>
         <p align="center">can email me <a href ="http://neutiquam.switchskate.net/freemail.php" >here</a>.  Please no spamming, because it is pointless and annoying.</p>
         <p>&nbsp;</p>
             
<p align ="center"><script type="text/javascript"><!--
google_ad_client = "pub-6326369933309468";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_color_border = "333333";
google_color_bg = "000000";
google_color_link = "FFFFFF";
google_color_url = "999999";
google_color_text = "CCCCCC";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
</p>
  <p align= "center"><font size ="1"><a href ="http://neutiquam.switchskate.net/gmail.php"><font color="#000000">click here</a></p>
<p><font color = "#000000">email, free web hosting gmail is the best mail service, who ever wants a gmail account plz submit a reason why i should invite you to ashtonreimer@gmail.com</p>



</html>