<html>

<head>
<meta name="keywords" content="soccer, webdesign, webhosting, web hosting, java, php, webdesign, html, programming">

<title>&#653; Ashty's Homepage &#653;</title>
</head>

<p>&nbsp;</p>
<body link="#33CC33" vlink="#33CC33" alink="#33CC33" topmargin="0" leftmargin="0" text="#33CC33" bgcolor="#000000">

<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" id="AutoNumber1">
    <tr>
      <td><img border="0" src="ASR.jpg" width="91" height="91"></td>
      <td>
<p align="center">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="404" height="64" id="banner" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="banner.swf" />
<param name="loop" value="true" />
<param name="menu" value="false" />
<param name="quality" value="high" />
<param name="bgcolor" value="#000000" />
<embed src="banner.swf" loop="true" menu="false" quality="high" bgcolor="#000000" width="800" height="100" name="banner" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" /></object>
    
<tr>
</tr>  
      </td>
      
          <td valign="top">

<p align="left"><b><font size="5" face="BlacklightD">&nbsp; </font>
<font size="4" face="BlacklightD">&nbsp;Links</font></b></p>

<p>&nbsp;<applet code="fphover.class" codebase="./" width="85" height="18">
  <param name="textcolor" value="#FFFFFF">
  <param name="text" value="Home">
  <param name="color" value="#008000">
  <param name="hovercolor" value="#33CC33">
  <param name="font" value="Dialog">
  <param name="fontstyle" value="bold">
  <param name="url" valuetype="ref" value="http://neutiquam.switchskate.net/">
  <param name="effect" value="bevelIn">
  <param name="fontsize" value="12">
  <param name="target" value ="_self">
</applet></p>
<p>&nbsp;<applet code="fphover.class" codebase="./" width="85" height="18">
  <param name="textcolor" value="#FFFFFF">
  <param name="color" value="#008000">
  <param name="hovercolor" value="#33CC33">
  <param name="font" value="Dialog">
  <param name="fontstyle" value="bold">
  <param name="effect" value="bevelIn">
  <param name="text" value="Downloads">
  <param name="url" valuetype="ref" value="http://neutiquam.switchskate.net/error2.php">
  <param name="fontsize" value="12">
  <param name="target" value ="_self">
</applet></p>

<p>&nbsp;<applet code="fphover.class" codebase="./" width="85" height="18">
  <param name="textcolor" value="#FFFFFF">
  <param name="color" value="#008000">
  <param name="hovercolor" value="#33CC33">
  <param name="font" value="Dialog">
  <param name="fontstyle" value="bold">
  <param name="effect" value="bevelIn">
  <param name="text" value="Games">
  <param name="url" valuetype="ref" value="http://neutiquam.switchskate.net/error2.php">
  <param name="fontsize" value="12">
  <param name="target" value ="_self">
</applet></p>

<p>&nbsp;<applet code="fphover.class" codebase="./" width="85" height="18">
  <param name="textcolor" value="#FFFFFF">
  <param name="color" value="#008000">
  <param name="hovercolor" value="#33CC33">
  <param name="font" value="Dialog">
  <param name="fontstyle" value="bold">
  <param name="effect" value="bevelIn">
  <param name="text" value="Contact">
  <param name="url" valuetype="ref" value="http://neutiquam.switchskate.net/contact.php">
  <param name="fontsize" value="12">
  <param name="target" value ="_self">
</applet></p>

&nbsp;</td>
      <td>
<p align="center">
<font size="2">
<marquee scrolldelay="5" width="293" height="25" style="font-family: BlacklightD; color: #00CC00" >Welcome to Ashton Reimer.tk&nbsp; Site is still underconstruction feel free to submit a comment or question.&nbsp; Email is webmaster@ashtonreimer.tk</marquee></font></p>
<p align="center">
<font face="BlacklightD" size="2">I've been working on this site in my spare time so it 
has been coming </font></p>
<p align="center">
<font face="BlacklightD" size="2">together slowly but surely.&nbsp; If you have any ideas for my 
page that you wanna </font></p>
<p align="center">
<font face="BlacklightD" size="2">share then please submit it to me.&nbsp; </font></p>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100" id="AutoNumber2" height="250" bgcolor="#000000">
    <tr>
      <td height="236">
<p align="left">
<font face="BlacklightD">To Do List</font></p>
<p align="left">
<font face="BlacklightD" size="2">-add a games page&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</font></p>
<p align="left">
<font face="BlacklightD" size="2">-add a downloads page</font></p>
<p align="left">
<font face="BlacklightD" size="2">-improve looks of page</font></p>
<p align="left">
<font face="BlacklightD" size="2">-possible photogallery?</font></p>
      <p>&nbsp;</td>
      <td height="236">
      <html>
<head>
	<title>Email</title>
</head>

<body>

<form name="CommentForm" action="">

 <p align="center"><input type="input" name="Title" size="20" value="Comments Title" style="font-family: BlacklightD">

</p>
 
 <p align="center">&nbsp;<textarea name="Comments" rows=10 cols=31 style="font-family: BlacklightD" >Enter Comments Here</textarea>

</p>
 
 <p align="center">&nbsp;<input type="submit" value="Submit" name="submit" style="font-family: BlacklightD">

</p>
	  

</form>

<?php

$MailTitle = "Comment - $Title";
$MailTo = "ashtonreimer@gmail.com";

if (isset ($submit)) {

   if (mail($MailTo ,$MailTitle ,$Comments)) {
   	  echo "<script> window.location.replace ('http://neutiquam.switchskate.net/mail.php'); </script>";
   } else {
   	  echo "<script> window.location.replace ('http://neutiquam.switchskate.net/error.php'); </script>";
   }

}

?>
</body>
</html>

      
      <p></form></td>
      <td height="236">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
</td>
       </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
  </center>
</div>

<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" id="AutoNumber3">
    <tr>
      <td>
      <meta name="keywords" content="soccer, webdesign, webhosting, web hosting, java, php, webdesign, html, programming">

   <script type="text/javascript"><!--
google_ad_client = "pub-6326369933309468";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_color_border = "333333";
google_color_bg = "000000";
google_color_link = "FFFFFF";
google_color_url = "999999";
google_color_text = "CCCCCC";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>

</td>
    </tr>
  </table>
  </center>
</div>

</body>

</html>