<html>
<head>
<title>Success Processing Email</title>
 <meta name="keywords" content="soccer, webdesign, webhosting, web hosting, java, php, webdesign, html, programming">
</head>

<body bgcolor ="#000000">
<p align = "center">
 <script type="text/javascript"><!--
google_ad_client = "pub-6326369933309468";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_color_border = "333333";
google_color_bg = "000000";
google_color_link = "FFFFFF";
google_color_url = "999999";
google_color_text = "CCCCCC";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
</p>

<p align= "center"><font color="#33CC33">Email Sent Click Thank you For Your Comment</p>

<p align= "center"><a href="http://neutiquam.switchskate.net/"><font color="#33CC33">Click Here <a>To Go Back</p>

 <p><font color = "#000000">soccer, webdesign, webhosting, web hosting, java, php, webdesign, html, programming</font></p>
</html>