<?php require ("http://www.switchskate.net/cp/handlers/header2.php");?>
<center>
<br>
<br>
<br>
<br>
<form action="4293.php" method="post">
<select name="what">
    <option value="tricktips" selected>Skate - Trick Tip
    <option value="reviews" >Skate - Review
    <option value="articles" >Skate - Article
    <option value="storys" >Skate - Skate Story
	<option value="sblinks" >Skate - Links
</select>
<input type="submit" value="submit" name="submit">
</form>

</body>