<!DOCTYPE XHTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html>
	<head>
	
		<title> Switch Skate -Your top skateboarding reference- </title>
		<meta name="Author" content="Adam Knox">
		<meta name="Keywords" content="">
		<meta name="Description" content="">
	
		<style type="text/css">
			
			body {
				background-color:#3D526D;
				margin-top:20px;
				font-family:Tahoma;
			}

			td#contentbox {
				background-image:url("http://www.switchskate.net/2005/images/ctboxbg.gif");
				color:#FFFFFF;
				border:1px solid #FFFFFF;
			}

			td#alt1 {
				border:1px solid #FFFFFF;
				color:#F4F4F4;
				background-color:#6C88B0;
			}

			table#side {
				background-color:#405676;
				color:#FFFFFF;
				width:120px;			
			}

			table#center {
				background-color:#405676;
				color:#FFFFFF;
				width:510px;			
			}

			a {
				color:#FFFFFF;
				text-decoration:none;
			}

			a:hover {
				color:#000000;
				text-decoration:none;
			}


		</style>

	</head>
	<body>
	
		<table width="750" align="center">
			<tr>
				<td>
					<img src="http://www.switchskate.net/2005/images/headerwhole.gif"></img>
				</td>
			</tr>
			<tr>
				<td>
					
					<table>
						<tr>
							<td valign="top">				
								
								<table id="side">
									<tr>
										<td id="contentbox">
											Navigation
										</td>
									</tr>
									<tr>
										<td id="alt1">
											<a href="">Trick Tips</a> ()<br />
											<a href="">Glossary</a> ()<br />
											<a href="">Reviews</a> ()<br />
											<a href="">Articles</a> ()<br />
											<a href="">Pictures</a> ()<br />
											<a href="">Ramp Plans</a> ()<br />
											<a href="">Links</a> ()<br />
											<br />
											<a href="">Tutorials</a> ()<br />
											<a href="">Reviews</a> ()<br />
											<a href="">Links</a> ()<br />
											<a href="">Scripts</a> ()<br />
											<a href="">Wallpaper</a> ()<br />
										</td>
									</tr>
								</table>

								<table id="side">
									<tr>
										<td id="contentbox">
											Advertisement
										</td>
									</tr>
									<tr>
										<td id="alt1">

											<table border='0' cellspacing='0' width='110' height='240'>
												<tr>
													<td valign='middle' align='center'>
														<script language="javascript1.2" type="text/javascript" src="http://search.revenuepilot.com/servlet/search?mode=js&perpage=1&filter=off&id=14269&tid=1&sid=0&skip=0&keyword=web hosting&by=off"></script>
													</td>
												</tr>
											</table>

										</td>
									</tr>
								</table>

								<table id="side">
									<tr>
										<td id="contentbox">
											Theme Chooser
										</td>
									</tr>
									<tr>
										<td id="alt1">

											<form method="post" action="">
												<input type="text" />
												<>
													<option>
													<option>
												</>

											</form>

										</td>
									</tr>
								</table>
							
							</td>
							<td valign="top">
								
								<table id="center">
									<tr>
										<td id="contentbox">
											Content
										</td>
									</tr>
									<tr>
										<td id="alt1">
											<!--\/ Content below here \/-->
											







											<!--/\ Content above here /\-->
										</td>
									</tr>
								</table>
		
							</td>
							<td valign="top">

								<table id="side">
									<tr>
										<td id="contentbox">
											Members
										</td>
									</tr>
									<tr>
										<td id="alt1">
											<a href="">Control Panel</a> <br />
											<a href="">Members Forum</a> <br />
											<a href="">Chat Line</a> <br />
											<a href="">Submit Content</a> <br />
											<a href="">Suggestions</a> <br />
										</td>
									</tr>
								</table>

								<table id="side">
									<tr>
										<td id="contentbox">
											Advertisement
										</td>
									</tr>
									<tr>
										<td id="alt1">
											<a href="https://secure.revenuepilot.com/jsp/home.jsp?id=14269"><img src="http://www.revenuepilot.com/userimages/referralbanners/banner5.gif" border="0" width="110" height="600" /></a>

										</td>
									</tr>
								</table>

							</td>						
						</tr>
					</table>
		
				</td>
			</tr>
			<tr>
				<td>
					Footer
				</td>
			</tr>
		</table>
	
	</body>
</html>
