<? require("../shared.inc.php"); ?>

<html>
<head>
<title>Help</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table width="95%" border="0" align="center">
  <tr bgcolor="#000099"> 
    <td> 
      <div align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">
	   <? echo "$site_name";?> 
        Click Through Help</font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td> 
      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><br>
        <b>and: </b><font size="1"><i>(end date)</i></font> </font></p>
      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Select the 
        end date with this dropdown box. This date <b>is</b> included in the statistics.</font></p>
      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">If you want 
        click through stats for only one day select the same date in both dropdown 
        boxes.</font></p>
    </td>
  </tr>
</table>
</body>
</html>
