<? require("../shared.inc.php"); ?>

<html>
<head>
<title>Help</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table width="95%" border="0" align="center">
  <tr bgcolor="#000099"> 
    <td> 
      <div align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">
	   <? echo "$site_name";?> 
        Click Through Help</font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td> 
      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><br>
        <br>
        <b>Raw clicks:</b><br>
        <br>
        The total number of times the page has been selected.<br>
        </font></p>
      </td>
  </tr>
</table>
</body>
</html>
