<?php
/* $Id: memcp.php,v 1.17.2.20 2004/10/24 07:52:57 ajv Exp $ */
/*
    XMB 1.9
    © 2001 - 2004 Aventure Media & The XMB Development Team
    http://www.aventure-media.co.uk
    http://www.xmbforum.com

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

require "header.php";

loadtemplates('footer_load', 'footer_querynum', 'footer_phpsql', 'footer_totaltime','memcp_profile_avatarurl', 'memcp_home_themes', 'memcp_profile_avatarlist','memcp_profile','memcp_favs_row','memcp_favs_none','memcp_favs','memcp_subscriptions_row','memcp_subscriptions_none','memcp_subscriptions','buddylist_buddy_online','buddylist_buddy_offline','memcp_home_u2u_row','memcp_home_u2u_none','memcp_home','memcp_home_favs_none','member_home_sig','header','footer','css','memcp_favs_button','memcp_subscriptions_button');
smcwcache();
eval("\$css = \"".template("css")."\";");

$favs = NULL;
$buddys = NULL;

// Determine the navigation

$action = isset($action) ? $action : '';
switch ($action) {
    case "profile":
        nav('<a href="memcp.php">'.$lang['textusercp'].'</a>');
        nav($lang['texteditpro']);
        break;

    case "subscriptions":
        nav('<a href="memcp.php">'.$lang['textusercp'].'</a>');
        nav($lang['textsubscriptions']);
        break;

    case "ct":
        nav('<a href="memcp.php">'.$lang['textusercp'].'</a>');
        nav($lang['ct_name']);
        break;
		
    case "favorites":
        nav('<a href="memcp.php">'.$lang['textusercp'].'</a>');
        nav($lang['textfavorites']);
        break;

    default:
        nav($lang['textusercp']);
        break;
}


/**
* makenav() - Create the user control panel navigation links
*
* Create the user control panel navigation links in HTML
*
* @param    $current	current URI we are viewing from (can be one of blank (default), profile, subscriptions, or favorites)
* @return   no return value
*/
function makenav($current) {
    global $bordercolor, $tablewidth, $borderwidth, $tablespacing, $altbg1, $altbg2, $lang;

    ?>
    <table cellpadding="0" cellspacing="0" border="0" bgcolor="<?php echo $bordercolor?>" width="<?php echo $tablewidth?>" align="center"><tr><td>
    <table cellpadding="4" cellspacing="1" border="0" width="100%">
    <tr align="center" class="tablerow">

    <?php

    if ($current == "") {
        echo "<td bgcolor=\"$altbg1\" width=\"15%\" class=\"ctrtablerow\">" .$lang['textmyhome']. "</td>";
    } else {
        echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"memcp.php\">" .$lang['textmyhome']. "</a></td>";
    }

    if ($current == "profile") {
        echo "<td bgcolor=\"$altbg1\" width=\"15%\" class=\"ctrtablerow\">" .$lang['texteditpro']. "</td>";
    } else {
        echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"memcp.php?action=profile\">" .$lang['texteditpro']. "</a></td>";
    }

	if($current == "ct") {
        echo "<td bgcolor=\"$altbg1\" width=\"15%\" class=\"ctrtablerow\">" .$lang['ct_name']. "</td>";
    } else {
        echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"memcp.php?action=ct\">" .$lang['ct_name']. "</a></td>";
    }

    if ($current == "subscriptions") {
        echo "<td bgcolor=\"$altbg1\" width=\"15%\" class=\"ctrtablerow\">" .$lang['textsubscriptions']. "</td>";
    } else {
        echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"memcp.php?action=subscriptions\">" .$lang['textsubscriptions']. "</a></td>";
    }

    if ($current == "favorites") {
        echo "<td bgcolor=\"$altbg1\" width=\"15%\" class=\"ctrtablerow\">" .$lang['textfavorites']. "</td>";
    } else {
        echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"memcp.php?action=favorites\">" .$lang['textfavorites']. "</a></td>";
    }

    echo "<td bgcolor=\"$altbg2\" width=\"20%\" class=\"ctrtablerow\"><a href=\"#\" onclick=\"Popup('u2u.php', 'Window', 700, 450);\">" .$lang['textu2umessenger']. "</a></td>";
    echo "<td bgcolor=\"$altbg2\" width=\"15%\" class=\"ctrtablerow\"><a href=\"#\" onclick=\"Popup('buddy.php?', 'Window', 450, 400);\">" .$lang['textbuddylist']. "</a></td>";
    echo "<td bgcolor=\"$altbg2\" width=\"10%\" class=\"ctrtablerow\"><a href=\"faq.php\">" .$lang['helpbar']. "</a></td>";

    ?>
    </tr>
    </table>
    </td></tr></table><br />

    <?php
}

// Determine if user is logged in, if not send to login page
if ( X_GUEST ) {
    redirect('misc.php?action=login', 0);
    exit();
}

if ($action == "quicktheme") {
    $db->query("UPDATE $table_members SET theme='$newtheme' WHERE username='$xmbuser'");
    redirect('memcp.php', 0);
    exit;
}

// Start Profile Editor Code
if ($action == "profile") {
    eval("echo (\"".template('header')."\");");
    makenav($action);

    if (!isset($editsubmit)) {
        $member = $self;

        $checked = '';
        if ($member['showemail'] == "yes") {
            $checked = "checked=\"checked\"";
        }

        $newschecked = '';
        if ($member['newsletter'] == "yes") {
            $newschecked = "checked=\"checked\"";
        }

        $uou2uchecked = '';
        if ($member['useoldu2u'] == "yes") {
            $uou2uchecked = "checked=\"checked\"";
        }

        $ogu2uchecked = '';
        if ($member['saveogu2u'] == "yes") {
            $ogu2uchecked = "checked=\"checked\"";
        }

        $eouchecked = '';
        if ($member['emailonu2u'] == "yes") {
            $eouchecked = "checked=\"checked\"";
        }

        $invchecked = '';
        if ($member['invisible'] == 1) {
            $invchecked = "checked=\"checked\"";
        }

        $currdate = gmdate("$timecode", time()+ ($addtime * 3600));
        eval($lang['evaloffset']);

        $timezone1 = $timezone2 = $timezone3 = $timezone4 = $timezone5 = $timezone6 = "";
        $timezone7 = $timezone8 = $timezone9 = $timezone10 = $timezone11 = $timezone12 = "";
        $timezone13 = $timezone14 = $timezone15 = $timezone16 = $timezone17 = $timezone18 = "";
        $timezone19 = $timezone20 = $timezone21 = $timezone22 = $timezone23 = $timezone24 = "";
        $timezone25 = $timezone26 = $timezone27 = $timezone28 = $timezone29 = $timezone30 = "";
        $timezone31 = $timezone32 = $timezone33 = "";

        if ($member['timeoffset'] == "-12") { $timezone1 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-11") { $timezone2 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-10") { $timezone3 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-9") { $timezone4 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-8") { $timezone5 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-7") { $timezone6 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-6") { $timezone7 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-5") { $timezone8 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-4") { $timezone9 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-3.5") { $timezone10 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-3") { $timezone11 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-2") { $timezone12 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "-1") { $timezone13 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "0") { $timezone14 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "1") { $timezone15 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "2") { $timezone16 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "3") { $timezone17 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "3.5") { $timezone18 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "4") { $timezone19 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "4.5") { $timezone20 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "5") { $timezone21 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "5.5") { $timezone22 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "5.75") { $timezone23 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "6") { $timezone24 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "6.5") { $timezone25 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "7") { $timezone26 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "8") { $timezone27 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "9") { $timezone28 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "9.5") { $timezone29 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "10") { $timezone30 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "11") { $timezone31 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "12") { $timezone32 = "selected=\"selected\""; }
        elseif ($member['timeoffset'] == "13") { $timezone33 = "selected=\"selected\""; }

        $themelist = "<select name=\"thememem\">\n<option value=\"0\">" .$lang['textusedefault']. "</option>";
        $query = $db->query("SELECT themeid, name FROM $table_themes ORDER BY name ASC");
        while ($theme = $db->fetch_array($query)) {
            if ($theme['themeid'] == $member['theme']) {
                $themelist .= "<option value=\"" .$theme['themeid']. "\" selected=\"selected\">" .stripslashes($theme['name']). "</option>\n";
            } else {
                $themelist .= "<option value=\"" .$theme['themeid']. "\">" .stripslashes($theme['name']). "</option>\n";
            }
        }

        $themelist  .= "</select>";


        $langfileselect = "<select name=\"langfilenew\">\n";
        $dir = opendir("lang");
        while ($thafile = readdir($dir)) {
            if (is_file("lang/$thafile") && false !== strpos($thafile, '.lang.php')) {
                $thafile = str_replace(".lang.php", "", $thafile);
                if ($thafile == $member['langfile']) {
                    $langfileselect .= "<option value=\"" .$thafile. "\" selected=\"selected\">" .$thafile. "</option>\n";
                } else {
                    $langfileselect .= "<option value=\"" .$thafile. "\">" .$thafile. "</option>\n";
                }
            }
        }
        $langfileselect .= "</select>";

        $member['bday'] = str_replace(",", "", $member['bday']);
        $bday = explode(" ", $member['bday']);

        $sel0 = $sel1 = $sel2 = $sel3 = $sel4 = $sel5 = $sel6 = "";
        $sel7 = $sel8 = $sel9 = $sel10 = $sel11 = $sel12 = "";

        if ($bday['0'] == "") {
            $sel0 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textjan']) {
            $sel1 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textfeb']) {
            $sel2 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textmar']) {
            $sel3 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textapr']) {
            $sel4 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textmay']) {
            $sel5 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textjun']) {
            $sel6 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textjul']) {
            $sel7 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textaug']) {
            $sel8 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textsep']) {
            $sel9 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textoct']) {
            $sel10 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textnov']) {
            $sel11 = "selected=\"selected\"";
        } elseif ($bday['0'] == $lang['textdec']) {
            $sel12 = "selected=\"selected\"";
        }

        $dayselect = "<select name=\"day\">\n";
        $dayselect .= "<option value=\"\">&nbsp;</option>\n";
        for ($num = 1; $num <= 31; $num++) {
            if (isset($bday[1]) && $bday[1] == $num) {
                $dayselect .= "<option value=\"" .$num. "\" selected=\"selected\">" .$num. "</option>\n";
            } else {
                $dayselect .= "<option value=\"" .$num. "\">" .$num. "</option>\n";
            }
        }
        $dayselect .= "</select>";

        $check12 = $check24 = "";

        if ($member['timeformat'] == "24") {
            $check24 = "checked=\"checked\"";
        } else {
            $check12 = "checked=\"checked\"";
        }

        if ($sigbbcode == "on") {
            $bbcodeis = $lang['texton'];
        } else {
            $bbcodeis = $lang['textoff'];
        }

        if ($sightml == "on") {
            $sigallowhtml = "yes";
            $htmlis = $lang['texton'];
        } else {
            $sigallowhtml = "no";
            $htmlis = $lang['textoff'];
        }

		$avatar = '';
        if ($avastatus == "on") {
            eval("\$avatar = \"".template("memcp_profile_avatarurl")."\";");
        }

        if ($avastatus == "list") {
            $avatars = " <option value=\"\" />" .$lang['textnone']. "</option>  ";
            $dir1 = opendir("./images/avatars");
            while ($avatar1 = readdir($dir1)) {
                if (is_file("./images/avatars/" .$avatar1. "")) {
                    $avatars .= " <option value=\"./images/avatars/" .$avatar1. "\" />" .$avatar1. "</option>  ";
                }
            }

            $avatars = str_replace("value=\"" .$member['avatar']. "\"", "value=\"" .$member['avatar']. "\" SELECTED", $avatars);
            $avatarbox = "<select name=\"newavatar\" onchange=\"document.images.avatarpic.src =this[this.selectedIndex].value;\">" .$avatars. "</select>";
            eval("\$avatar = \"".template("memcp_profile_avatarlist")."\";");
            closedir($dir1);
        }

        if ( !isset($bday[2]) ) {
            $bday[2] = '';
        }

        eval("\$profile = \"".template("memcp_profile")."\";");
        $profile = stripslashes($profile);
        echo $profile;
    }

    if (isset($editsubmit)) {
        reset($self);
        $member = $self;

        if (!$member['username']) {
            error($lang['badname'], false);
        }

        if ($xmbpw != $member['password']) {
            error($lang['textpwincorrect'], false);
        }

        if ( isset($newemail) && ( !isset($_POST['newemail']) || isset($_GET['newemail'])) ) {
			$auditaction = $_SERVER['REQUEST_URI'];
			$aapos = strpos($auditaction, "?");
			if ( $aapos !== false ) {
				$auditaction = substr($auditaction, $aapos + 1);
			}
			$auditaction = addslashes("$onlineip|#|$auditaction");
			audit($xmbuser, $auditaction, 0, 0, "Potential XSS exploit using newemail");
			die("Hack atttempt recorded in audit logs.");
		}

		if ( isset($newpassword) && (!isset($_POST['newpassword']) || isset($_GET['newpassword'])) ) {
			$auditaction = $_SERVER['REQUEST_URI'];
			$aapos = strpos($auditaction, "?");
			if ( $aapos !== false ) {
				$auditaction = substr($auditaction, $aapos + 1);
			}
			$auditaction = addslashes("$onlineip|#|$auditaction");
			audit($xmbuser, $auditaction, 0, 0, "Potential XSS exploit using newpassword");
			die("Hack atttempt recorded in audit logs.");
		}

        $showemail = ( isset($showemail) && $showemail == "yes" ) ? "yes" : "no";
        $newsletter = ( isset($newsletter) && $newsletter == "yes" ) ? "yes" : "no";
        $saveogu2u = ( isset($saveogu2u) && $saveogu2u == "yes" ) ? "yes" : "no";
        $emailonu2u = ( isset($emailonu2u) && $emailonu2u == "yes" ) ? "yes" : "no";
        $useoldu2u = ( isset($useoldu2u) && $useoldu2u == "yes" ) ? "yes" : "no";

        $bday = "$month $day, $year";

        if ($month == "" || $day == "" || $year == "") {
            $bday = "";
        }

        $newavatar      = isset($newavatar) ? ereg_replace(' ', '%20', $newavatar) : ''; // Problem with spaces in avatar url
        $avatar         = checkInput($newavatar, '', '', 'javascript', false);

        $memlocation    = isset($newmemlocation) ? checkInput($newmemlocation, '', '', 'javascript', false) : '';
        $icq            = isset($newicq) ? checkInput($newicq, '', '', 'javascript', false) : '';
        $yahoo          = isset($newyahoo) ? checkInput($newyahoo, '', '', 'javascript', false) : '';
        $aim            = isset($newaim) ? checkInput($newaim, '', '', 'javascript', false) : '';
        $msn            = isset($newmsn) ? checkInput($newmsn, '', '', 'javascript', false) : '';

        // Do not allow blank email addresses.
        if ( isset($newemail) ) {
			$newemail = trim($newemail);
			if ( $newemail != '' ) {
				$email = checkInput($newemail, '', '', 'javascript', false);
			} else {
				$email = $member['email'];
			}
        }

        $site           = isset($newsite) ? checkInput($newsite, '', '', 'javascript', false) : '';
        $webcam         = isset($newwebcam) ? checkInput($newwebcam, '', '', 'javascript', false) : '';
        $bio            = isset($newbio) ? checkInput($newbio, '', '', 'javascript', false) : '';
        $bday           = isset($bday) ? checkInput($bday, '', '', 'javascript', false) : '';
        $mood           = isset($newmood) ? checkInput($newmood, '', '', 'javascript', false) : '';
        $pstatus        = isset($newpstatus) ? checkInput($newpstatus, '', '', 'javascript', false) : '';
        $sig            = isset($newsig) ? checkInput($newsig, '', $SETTINGS['sightml'], '', false) : '';

        $sig            = addslashes($sig);
        $bio            = addslashes($bio);
        $memlocation    = addslashes($memlocation);

        $invisible      = (isset($newinv) && $newinv == 1) ? 1 : 0;
        $showemail      = (isset($newshowemail) && $newshowemail == 'yes') ? 'yes' : 'no';
        $newsletter     = (isset($newnewsletter) && $newnewsletter == 'yes') ? 'yes' : 'no';

        $size = @getimagesize($avatar);
        $max_size = explode('x', $SETTINGS['max_avatar_size']);
        if ($size === false && ($max_size[0] > 0 && $max_size[1] > 0)) {
            $avatar = '';
        } elseif (($max_size[0] > 0 && $max_size[1] > 0) && ($size['0'] > $max_size['0'] || $size['1'] > $max_size['1'])) {
            error($lang['avatar_too_big'] . $SETTINGS['max_avatar_size'] . 'px', false);
        }

		$newpassword = trim($newpassword);
		$newpasswordcf = trim($newpasswordcf);

	    if ($newpassword != '' || $newpasswordcf != '' ) {
			if ($newpassword != $newpasswordcf ) {
				error($lang['pwnomatch'], false);
			}

            $newpassword = md5($newpassword);

            $pwtxt = "password='$newpassword',";

            $currtime = time() - (86400*30);
            put_cookie("xmbuser", $username, $currtime, $cookiepath, $cookiedomain);
            put_cookie("xmbpw", $password, $currtime, $cookiepath, $cookiedomain);
        } else {
            $pwtxt = '';
        }

        $db->query("UPDATE $table_members SET $pwtxt email='$email', site='$site', aim='$aim', location='$memlocation', bio='$bio', sig='$sig', showemail='$showemail', timeoffset='$timeoffset1', icq='$icq', avatar='$avatar', yahoo='$yahoo', theme='$thememem', bday='$bday', langfile='$langfilenew', tpp='$tppnew', ppp='$pppnew', newsletter='$newsletter', timeformat='$timeformatnew', msn='$msn', dateformat='$dateformatnew', mood='$mood', invisible='$invisible', saveogu2u='$saveogu2u', emailonu2u='$emailonu2u', useoldu2u='$useoldu2u', webcam='$webcam' WHERE username='$xmbuser'");

        echo "<center><span class=\"mediumtxt \">" .$lang['usercpeditpromsg']. "</span></center>";
        redirect('memcp.php', 2.5, X_REDIRECT_JS);
    }
}

// Start Favorites
elseif ($action == "favorites") {
    eval("echo (\"".template('header')."\");");

    makenav($action);

    if (!isset($favsubmit) && isset($favadd) && is_numeric($favadd)) {
        $favadd = (int) $favadd;
        if ( $favadd == 0 ) {
            error($lang['fnasorry'], false);
        }
        $query = $db->query("SELECT tid FROM $table_favorites WHERE tid='$favadd' AND username='$xmbuser' AND type='favorite'");
        $favthread = $db->fetch_array($query);

        if ($favthread) {
            error($lang['favonlistmsg'], false);
        }

        $db->query("INSERT INTO $table_favorites ( tid, username, type ) VALUES ('$favadd', '$xmbuser', 'favorite')");
        echo "<center><span class=\"mediumtxt \">" .$lang['favaddedmsg']. "</span></center>";
        redirect('memcp.php?action=favorites', 2, X_REDIRECT_JS);
    }

    if (!isset($favadd) && !isset($favsubmit)) {
        $query = $db->query("SELECT f.*, t.fid, t.icon, t.lastpost, t.subject, t.replies FROM $table_favorites f, $table_threads t WHERE f.tid=t.tid AND f.username='$xmbuser' AND f.type='favorite' ORDER BY t.lastpost DESC");
        $favnum = 0;
        $favs = '';

        $tmOffset = ($timeoffset * 3600) + ($addtime * 3600);

        while ($fav = $db->fetch_array($query)) {
            $query2 = $db->query("SELECT name, fup, fid FROM $table_forums WHERE fid='$fav[fid]'");
            $forum = $db->fetch_array($query2);
            $lastpost = explode("|", $fav['lastpost']);
            $dalast = $lastpost['0'];
            $lastpost['1'] = "<a href=\"member.php?action=viewpro&amp;member=".rawurlencode($lastpost['1'])."\">$lastpost[1]</a>";
            $lastreplydate = gmdate($dateformat, $lastpost['0'] + $tmOffset);
            $lastreplytime = gmdate($timecode, $lastpost['0'] + $tmOffset);
            $lastpost = "" .$lang['lastreply1']. " " .$lastreplydate. " " .$lang['textat']. " " .$lastreplytime. " " .$lang['textby']. " " .$lastpost['1']. "";
            $fav['subject'] = stripslashes(censor($fav['subject']));

            if ($fav['icon'] != "") {
                $fav['icon'] = "<img src=\"" .$smdir. "/" .$fav['icon']. "\" />";
            } else {
                $fav['icon'] = "&nbsp;";
            }

            $favnum++;
            eval("\$favs .= \"".template("memcp_favs_row")."\";");
        }

        // Fix By John Briggs
        $favsbtn = '';
        if ($favnum != 0) {
            eval("\$favsbtn = \"".template("memcp_favs_button")."\";");
        }
        // Fix By John Briggs

        if ($favnum == 0) {
            eval("\$favs = \"".template("memcp_favs_none")."\";");
        }

        eval("\$favorites = \"".template("memcp_favs")."\";");
        $favorites = stripslashes($favorites);
        echo $favorites;
    }

    if (!isset($favadd) && isset($favsubmit)) {
        $query = $db->query("SELECT tid FROM $table_favorites WHERE username='$xmbuser' AND type='favorite'");
        while($fav = $db->fetch_array($query)) {
            $delete = "delete" .$fav['tid']. "";
            $delete = "${$delete}";
            $db->query("DELETE FROM $table_favorites WHERE username='$xmbuser' AND tid='$delete' AND type='favorite'");
        }

        echo "<center><span class=\"mediumtxt \">" .$lang['favsdeletedmsg']. "</span></center>";
        redirect('memcp.php?action=favorites', 2, X_REDIRECT_JS);
    }
}

// Start Subscriptions
elseif ($action == "subscriptions") {
    eval("echo (\"".template('header')."\");");

    makenav($action);

    if (!isset($subadd) && !isset($subsubmit)) {
        $query = $db->query("SELECT f.*, t.fid, t.icon, t.lastpost, t.subject, t.replies FROM $table_favorites f, $table_threads t WHERE f.tid=t.tid AND f.username='$xmbuser' AND f.type='subscription' ORDER BY t.lastpost DESC");
        $subnum = 0;
        $subscriptions = '';

        $tmOffset = ($timeoffset * 3600) + ($addtime * 3600);

        while ($fav = $db->fetch_array($query)) {
            $query2 = $db->query("SELECT name, fup, fid FROM $table_forums WHERE fid='$fav[fid]'");
            $forum = $db->fetch_array($query2);
            $lastpost = explode("|", $fav['lastpost']);
            $dalast = $lastpost['0'];
            $lastpost['1'] = "<a href=\"member.php?action=viewpro&amp;member=".rawurlencode($lastpost['1'])."\">$lastpost[1]</a>";
            $lastreplydate = gmdate($dateformat, $lastpost['0'] + $tmOffset);
            $lastreplytime = gmdate($timecode, $lastpost['0'] + $tmOffset);
            $lastpost = "" .$lang['lastreply1']. " " .$lastreplydate. " " .$lang['textat']. " " .$lastreplytime. " " .$lang['textby']. " " .$lastpost['1']. "";
            $fav['subject'] = stripslashes(censor($fav['subject']));

            if ($fav['icon'] != "") {
                $fav['icon'] = "<img src=\"" .$smdir. "/" .$fav['icon']. "\" />";
            } else {
                $fav['icon'] = "&nbsp;";
            }
            $subnum++;
            eval("\$subscriptions .= \"".template("memcp_subscriptions_row")."\";");
        }

        // Fix By John Briggs
        $subsbtn = '';
        if ($subnum != 0) {
            eval("\$subsbtn = \"".template("memcp_subscriptions_button")."\";");
        }
        // Fix By John Briggs

        if ($subnum == 0) {
            eval("\$subscriptions = \"".template("memcp_subscriptions_none")."\";");
        }

        eval("\$page = \"".template("memcp_subscriptions")."\";");
        $page = stripslashes($page);
        echo $page;

    } elseif (isset($subadd) && !isset($subsubmit)) {
        $query = $db->query("SELECT count(tid) FROM $table_favorites WHERE tid='$subadd' AND username='$xmbuser' AND type='subscription'");
        if ($db->result($query,0) == 1) {
            error($lang['subonlistmsg'], false);
        } else {
            $db->query("INSERT INTO $table_favorites ( tid, username, type ) VALUES ('$subadd', '$xmbuser', 'subscription')");
            echo "<center><span class=\"mediumtxt \">$lang[subaddedmsg]</span></center>";
            redirect('memcp.php?action=subscriptions', 2, X_REDIRECT_JS);
        }
    } elseif (!isset($subadd) && isset($subsubmit)) {
        $query = $db->query("SELECT tid FROM $table_favorites WHERE username='$xmbuser' AND type='subscription'");
        while ($sub = $db->fetch_array($query)) {
            $delete = "delete" .$sub['tid']. "";
            $delete = "${$delete}";
            $db->query("DELETE FROM $table_favorites WHERE username='$xmbuser' AND tid='$delete' AND type='subscription'");
        }

        echo "<center><span class=\"mediumtxt \">" .$lang['subsdeletedmsg']. "</span></center>";
        redirect('memcp.php?action=subscriptions', 2, X_REDIRECT_JS);
    }
}
// Start Custom Themes
elseif($action == "ct") { 
    $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center">
    <tr><td bgcolor="'.$bordercolor.'">
    <table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';
    switch($s) {
        case 'admin':
            if(!X_ADMIN) {
                redirect("memcp.php?action=ct", 0);
            }else{
                if(FunForum_su($SETTINGS[CustomTheme], 1) == "1"){ $fcto1y = 'checked'; $fcto1n = ''; }else{ $fcto1y = ''; $fcto1n = 'checked'; }
                if(FunForum_su($SETTINGS[CustomTheme], 2) == "1"){ $fcto2y = 'checked'; $fcto2n = ''; }else{ $fcto2y = ''; $fcto2n = 'checked'; }
                if(FunForum_su($SETTINGS[CustomTheme], 3) == "1"){ $fcto3y = 'checked'; $fcto3n = ''; }else{ $fcto3y = ''; $fcto3n = 'checked'; }
                if(FunForum_su($SETTINGS[CustomTheme], 4) == "1"){ $fcto4y = 'checked'; $fcto4n = ''; }else{ $fcto4y = ''; $fcto4n = 'checked'; }

                $page .= '<form method="post" action="memcp.php?action=ct&s=admin">';
                $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_name].' » Admin Area</font></strong></td></tr>';

                $page .= '</table></td></tr></table> <br />';
                $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center"><tr><td bgcolor="'.$bordercolor.'"><table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';

                if(!$ctsubmit && !$ctcancel){
                    $tquery = $db->query("SELECT CustomTheme FROM ".$tablepre."members_themes WHERE uid='0'"); $dtheme = $db->result($tquery, 0); 
                    $themelist = '<select name="ntname">\n';
                    $query = $db->query("SELECT themeid,name FROM $table_themes");
                    while($themeinfo = $db->fetch_array($query)) {
                     if($themeinfo['themeid'] == $dtheme){
                     $themelist .= '<option value="'.$themeinfo[themeid].'" selected>'.$themeinfo[name].'</option>\n';
                     }else{
                     $themelist .= '<option value="'.$themeinfo[themeid].'">'.$themeinfo[name].'</option>\n';
                     }
                    }
                    $themelist .= '</select>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o16].'</td>
                     <td colspan="2">'.$lang[ct_o28].''.$themelist.'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o29].'</td>
                     <td colspan="2"> <input type="radio" value="1" '.$fcto1y.' name="fcto1new" /> '.$lang[textyes].'           <input type="radio" value="0" '.$fcto1n.' name="fcto1new" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o30].'</td>
                     <td colspan="2"> <input type="radio" value="1" '.$fcto2y.' name="fcto2new" /> '.$lang[textyes].'           <input type="radio" value="0" '.$fcto2n.' name="fcto2new" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o32].'</td>
                     <td colspan="2"> <input type="radio" value="1" '.$fcto3y.' name="fcto3new" /> '.$lang[textyes].'           <input type="radio" value="0" '.$fcto3n.' name="fcto3new" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o33].'</td>
                     <td colspan="2"> <input type="radio" value="1" '.$fcto4y.' name="fcto4new" /> '.$lang[textyes].'           <input type="radio" value="0" '.$fcto4n.' name="fcto4new" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg1.'" class="tablerow">
                     <td>'.$lang[ct_o04].'</td>
                     <td colspan="2" align="center"><input type="submit" value="'.$lang[ct_b01].'" name="ctsubmit">           <input type="submit" value="'.$lang[ct_b02].'" name="ctcancel"></td>
                    </tr>';
                }elseif($ctsubmit){
                    $querg = $db->query("SELECT * FROM $table_themes WHERE themeid='$ntname'");
                    $t = $db->fetch_array($querg);
                    $db->query("UPDATE ".$tablepre."members_themes SET CustomTheme='$t[themeid]', name='$t[name]', bgcolor='$t[bgcolor]', altbg1='$t[altbg1]', altbg2='$t[altbg2]', link='$t[link]', bordercolor='$t[bordercolor]', header='$t[header]', headertext='$t[headertext]', top='$t[top]', catcolor='$t[catcolor]', tabletext='$t[tabletext]', text='$t[text]', borderwidth='$t[borderwidth]', tablewidth='$t[tablewidth]', tablespace='$t[tablespace]', fontsize='$t[fontsize]', font='$t[font]', boardimg='$t[boardimg]', imgdir='$t[imgdir]', smdir='$t[smdir]', cattext='$t[cattext]' WHERE uid='0'");

                    $db->query("UPDATE $table_settings SET CustomTheme='$fcto1new|$fcto2new|$fcto3new|$fcto4new'");
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o17].'</td></tr>';
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }elseif($ctcancel){
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o15].'</td></tr>';
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }
                $page .= '</form>';
            }
        break;
        case 'activate':
            $page .= '<tr><td '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_name].' » Activation</font></strong></td></tr>';
            $query = $db->query("SELECT themeid FROM ".$tablepre."members_themes WHERE uid = '$self[uid]'"); 
            if($e = $db->fetch_array($query)) { 
                $page .= '<tr><td bgcolor="'.$altbg2.'" class="tablerow" align="center">'.$lang[ct_o09].'<br /><br /><input type="button" value="'.$lang[ct_o13].'" onClick="location.href=\'memcp.php?action=ct\'" /></td></tr>';
            }else{ 
                if(!$do){
                    $page .= '<tr><td bgcolor="'.$altbg2.'" class="tablerow" align="center">'.$lang[ct_o10].'<br /><br /><input type="button" value="'.$lang[ct_o11].'" onClick="location.href=\'memcp.php?action=ct&s=activate&do=it\'" /></td></tr>';
                }else{
                    $querg = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE uid='0'");
                    $t = $db->fetch_array($querg);
                    if(FunForum_su($SETTINGS[CustomTheme], 4) == "1"){ 
                     if(FunForum_su($SETTINGS[CustomTheme], 3) == "1"){ $t_name = $t[name]; }
                     else{ $t_name = "$self[username]$lang[ct_o31]"; $t_name = addslashes($t_name); }
                     $query = "INSERT INTO ".$tablepre."members_themes (themeid, uid, CustomTheme, name, bgcolor, altbg1, altbg2, link, bordercolor, header, headertext, top, catcolor, tabletext, text, borderwidth, tablewidth, tablespace, font, fontsize, boardimg, imgdir, smdir, cattext) VALUES ('', '$self[uid]', '0|0', '$t_name', '$t[bgcolor]', '$t[altbg1]', '$t[altbg2]', '$t[link]', '$t[bordercolor]', '$t[header]', '$t[headertext]', '$t[top]', '$t[catcolor]', '$t[tabletext]', '$t[text]', '$t[borderwidth]', '$t[tablewidth]', '$t[tablespace]', '$t[font]', '$t[fontsize]', '$t[boardimg]', '$t[imgdir]', '$t[smdir]', '$t[cattext]')";
                    }else{
                     if(FunForum_su($SETTINGS[CustomTheme], 3) == "0"){ $t_name = str_replace("*Username*", $self[username], $lang[ct_o31]); $t_name = addslashes($t_name); }
                     $query = "INSERT INTO ".$tablepre."members_themes (themeid, uid, CustomTheme, name, bgcolor, altbg1, altbg2, link, bordercolor, header, headertext, top, catcolor, tabletext, text, borderwidth, tablewidth, tablespace, font, fontsize, boardimg, imgdir, smdir, cattext) VALUES ('', '$self[uid]', '0|0', '$t_name', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')";
                    }
                    $result = mysql_query($query) or die("Query failed : " . mysql_error());

                    $page .= '<tr><td bgcolor="'.$altbg2.'" class="tablerow" align="center">'.$lang[ct_o12].'<br /><br /><input type="button" value="'.$lang[ct_o13].'" onClick="location.href=\'memcp.php?action=ct\'" /></td></tr>';
                }
            }
        break;
        default:
            $page .= '<form method="post" action="memcp.php?action=ct">';
            $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_name].'</font></strong></td></tr>';

            if(FunForum_su($self[CustomTheme], 1) == "1"){ $usectyes = "checked"; $usectno=''; }else{ $usectno = "checked"; $usectyes=''; } 
            if(FunForum_su($self[CustomTheme], 2) == "1"){ $sharectyes = "checked"; $sharectno=''; }else{ $sharectno = "checked"; $sharectyes=''; } 
            $query = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE uid = '$self[uid]'"); 
            if($t = $db->fetch_array($query)) { 
                if(!$ctsubmit && !$ctother && !$ctcancel && !$ctdefault){
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3">'.$lang[ct_o34].'</td></tr>';


                    $page .= '</table></td></tr></table> <br />';
                    $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center"><tr><td bgcolor="'.$bordercolor.'"><table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';


                    $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_o21].'</font></strong></td></tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3">'.$lang[ct_o35].'</td></tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td width="67%">'.$lang[ct_o01].'</td>
                     <td width="33%" colspan="2"> <input type="radio" value="1" '.$usectyes.' name="usectnew" /> '.$lang[textyes].'           <input type="radio" value="0" '.$usectno.' name="usectnew" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o02].'</td>
                     <td colspan="2"> <input type="radio" value="1" '.$sharectyes.' name="sharectnew" /> '.$lang[textyes].'           <input type="radio" value="0" '.$sharectno.' name="sharectnew" /> '.$lang[textno].' </td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o04].'<input type="hidden" value="'.$t[themeid].'" name="theid" /></td>
                     <td colspan="2" align="center"><input type="submit" value="'.$lang[ct_b01].'" name="ctsubmit">           <input type="submit" value="'.$lang[ct_b02].'" name="ctcancel"></td>
                    </tr>';


                    $page .= '</table></td></tr></table> <br />';
                    $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center"><tr><td bgcolor="'.$bordercolor.'"><table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';


                    $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_o23].'</font></strong></td></tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3">'.$lang[ct_o36].'</td></tr>';
                    $querg = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE uid='$self[uid]'");
                    $t = $db->fetch_array($querg);
                    $quere = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE (themeid='1' AND uid='0')");
                    $extheme = $db->fetch_array($quere);
                    if(FunForum_su($SETTINGS[CustomTheme], 3) == "1"){ $fctna = ""; $t[name] = stripslashes($t[name]); $fctne = $lang[ct_o03].': '.$extheme[name]; }
                    else{ $fctna = "readonly"; $t[name] = "$self[username]$lang[ct_o31]"; }
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td width="33%">'.$lang[texthemename].'</td>
                     <td width="34%"><input type="text" value="'.$t[name].'" '.$fctna.' name="namenew" /></td>
                     <td width="33%">'.$fctne.'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o24].'</td>
                     <td><input type="text" value="'.$t[bgcolor].'" name="bgcolornew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[bgcolor].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textaltbg1].'</td>
                     <td><input type="text" value="'.$t[altbg1].'" name="altbg1new" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[altbg1].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textaltbg2].'</td>
                     <td><input type="text" value="'.$t[altbg2].'" name="altbg2new" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[altbg2].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textlink].'</td>
                     <td><input type="text" value="'.$t[link].'" name="linknew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[link].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textborder].'</td>
                     <td><input type="text" value="'.$t[bordercolor].'" name="bordercolornew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[bordercolor].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textheader].'</td>
                     <td><input type="text" value="'.$t[header].'" name="headernew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[header].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textheadertext].'</td>
                     <td><input type="text" value="'.$t[headertext].'" name="headertextnew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[headertext].'</td>
                    </tr>';
                    if(!strstr($extheme[top], ".")) { $exttop = '<br />http://domain.com/img/image.ext<br />'.$extheme[top]; } else { $exttop = '<br />http://domain.com/img/'.$extheme[top].'<br />#123456'; }
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o25].'</td>
                     <td><input type="text" value="'.$t[top].'" name="topnew" /></td>
                     <td>'.$lang[ct_o03].': '.$exttop.'</td>
                    </tr>';
                    if(!strstr($extheme[catcolor], ".")) { $extcatcl = '<br />http://domain.com/img/image.ext<br />'.$extheme[catcolor]; } else { $extcatcl = '<br />http://domain.com/img/'.$extheme[catcolor].'<br />#123456'; }
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o26].'</td>
                     <td><input type="text" value="'.$t[catcolor].'" name="catcolornew" /></td>
                     <td>'.$lang[ct_o03].': '.$extcatcl.'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textcattextcolor].'</td>
                     <td><input type="text" value="'.$t[cattext].'" name="cattextnew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[cattext].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[texttabletext].'</td>
                     <td><input type="text" value="'.$t[tabletext].'" name="tabletextnew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[tabletext].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[texttext].'</td>
                     <td><input type="text" value="'.$t[text].'" name="textnew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[text].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textborderwidth].'</td>
                     <td><input type="text" value="'.$t[borderwidth].'" name="borderwidthnew" size="2" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[borderwidth].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textwidth].'</td>
                     <td><input type="text" value="'.$t[tablewidth].'" name="tablewidthnew" size="3" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[tablewidth].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textspace].'</td>
                     <td><input type="text" value="'.$t[tablespace].'" name="tablespacenew" size="2" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[tablespace].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textfont].'</td>
                     <td><input type="text" value="'.$t[font].'" name="fnew" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[font].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[textbigsize].'</td>
                     <td><input type="text" value="'.$t[fontsize].'" name="fsizenew" size="4" /></td>
                     <td>'.$lang[ct_o03].': '.$extheme[fontsize].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o27].'</td>
                     <td><input type="text" value="'.$t[boardimg].'" name="boardlogonew" /></td>
                     <td>'.$lang[ct_o03].':<br />http://domain.ext/img/'.$extheme[boardimg].'</td>
                    </tr>';
                    if(FunForum_su($SETTINGS[CustomTheme], 1) == "1"){ 
                     $imgdirlist = '<input type="text" value="'.$t[imgdir].'" name="imgdirnew" />';
                    }else{
                     $imgdirlist = '<select name="imgdirnew">\n';
                     $query = $db->query("SELECT name, imgdir FROM $table_themes");
                     while($imgdirinfo = $db->fetch_array($query)) {
                         if($imgdirinfo[imgdir] == "$t[imgdir]"){
                         $imgdirlist .= '<option value="'.$imgdirinfo[imgdir].'" selected>'.$imgdirinfo[name].'</option>\n';
                         }else{
                         $imgdirlist .= '<option value="'.$imgdirinfo[imgdir].'">'.$imgdirinfo[name].'</option>\n';
                         }
                     }
                     $imgdirlist .= '</select>';
                    }
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[imgdir].'</td>
                     <td>'.$imgdirlist.'</td>
                     <td>'.$lang[ct_o03].': '.$extheme[imgdir].'</td>
                    </tr>';
                    if(FunForum_su($SETTINGS[CustomTheme], 2) == "1"){ 
                     $smdirlist = '<input type="text" value="'.$t[smdir].'" name="smdirnew" />';
                    }else{
                     $smdirlist = '<select name="smdirnew">\n';
                     $query = $db->query("SELECT DISTINCT smdir FROM $table_themes");
                     while($smdirinfo = $db->fetch_array($query)) {
                         if($smdirinfo[smdir] == "$t[imgdir]"){
                         $smdirlist .= '<option value="'.$smdirinfo[smdir].'" selected>'.$smdirinfo[smdir].'</option>\n';
                         }else{
                         $smdirlist .= '<option value="'.$smdirinfo[smdir].'">'.$smdirinfo[smdir].'</option>\n';
                         }
                     }
                     $smdirlist .= '</select>';
                    }
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[smdir].'</td>
                     <td>'.$smdirlist.'</td>
                     <td>'.$lang[ct_o03].': '.$extheme[smdir].'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o04].'<input type="hidden" value="'.$t[themeid].'" name="theid" /></td>
                     <td colspan="2" align="center"><input type="submit" value="'.$lang[ct_b01].'" name="ctsubmit">           <input type="submit" value="'.$lang[ct_b03].'" name="ctdefault">           <input type="submit" value="'.$lang[ct_b02].'" name="ctcancel"></td>
                    </tr>';


                    $page .= '</table></td></tr></table> <br />';
                    $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center"><tr><td bgcolor="'.$bordercolor.'"><table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';


                    $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_o22].'</font></strong></td></tr>';
                    $tquery = $db->query("SELECT name, uid FROM ".$tablepre."members_themes WHERE (uid!='$self[uid]' AND (CustomTheme='0|1' OR CustomTheme='1|1')) ORDER by name");
                    $tctsmtlist = '<select name="otheruid">\n';
                    $tctsmtlist .= '<option value="">'.$lang['ct_o38'].'</option>\n';
                    while($tctsmtinfo = $db->fetch_array($tquery)) {
                     $tctsmtlist .= '<option value="'.$tctsmtinfo[uid].'">'.stripslashes($tctsmtinfo[name]).'</option>\n';
                    }
                    $tctsmtlist .= '</select>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3">'.$lang[ct_o19].'</td></tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td>'.$lang[ct_o28].'</td>
                     <td colspan="2">'.$tctsmtlist.'</td>
                    </tr>';
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                     <td width="33%">'.$lang[ct_o04].'</td>
                     <td width="67%" colspan="2" align="center"><input type="submit" value="'.$lang[ct_b04].'" name="ctother"></td>
                    </tr>';


                    if(X_ADMIN){
                     $page .= '</table></td></tr></table> <br />';
                     $page .= '<table cellspacing="0" cellpadding="0" border="0" width="'.$tablewidth.'" align="center"><tr><td bgcolor="'.$bordercolor.'"><table border="0" cellspacing="'.$borderwidth.'" cellpadding="'.$tablespace.'" width="100%">';

                     $page .= '<tr><td colspan="3" '.$catbgcode.' class="category"><strong><font color="'.$cattext.'">'.$lang[ct_o37].'</font></strong></td></tr>';
                     $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow">
                         <td width="33%">'.$lang[ct_o04].'</td>
                         <td width="67%" colspan="2" align="center"><input type="button" value="'.$lang[ct_b06].'" onClick="location.href=\'memcp.php?action=ct&s=admin\'" /></td>
                     </tr>';
                    }

                }elseif($ctsubmit){
                    // we also look for a 'dot' (where an image is not allowed), so no-one can submit an URL
                    $usectnew = checkInput($usectnew, '', '', "script");         $usectnew = checkInput($usectnew, '', '', "."); 
                    $sharectnew = checkInput($sharectnew, '', '', "script"); $sharectnew = checkInput($sharectnew, '', '', "."); 
                    $namenew = checkInput($namenew, '', '', "script");                                          $namenew = addslashes($namenew);
                    $bgcolornew = checkInput($bgcolornew, '', '', "script");
                    $altbg1new = checkInput($altbg1new, '', '', "script");         $altbg1new = checkInput($altbg1new, '', '', "."); 
                    $altbg2new = checkInput($altbg2new, '', '', "script");         $altbg2new = checkInput($altbg2new, '', '', "."); 
                    $linknew = checkInput($linknew, '', '', "script");         $linknew = checkInput($linknew, '', '', "."); 
                    $bordercolornew = checkInput($bordercolornew, '', '', "script"); $bordercolornew = checkInput($bordercolornew, '', '', "."); 
                    $headernew = checkInput($headernew, '', '', "script");         $headernew = checkInput($headernew, '', '', "."); 
                    $headertextnew = checkInput($headertextnew, '', '', "script"); $headertextnew = checkInput($headertextnew, '', '', "."); 
                    $topnew = checkInput($topnew, '', '', "script"); 
                    $catcolornew = checkInput($catcolornew, '', '', "script"); 
                    $tabletextnew = checkInput($tabletextnew, '', '', "script"); $tabletextnew = checkInput($tabletextnew, '', '', "."); 
                    $textnew = checkInput($textnew, '', '', "script");         $textnew = checkInput($textnew, '', '', "."); 
                    $borderwidthnew = checkInput($borderwidthnew, '', '', "script"); $borderwidthnew = checkInput($borderwidthnew, '', '', "."); 
                    $tablewidthnew = checkInput($tablewidthnew, '', '', "script"); $tablewidthnew = checkInput($tablewidthnew, '', '', "."); 
                    $tablespacenew = checkInput($tablespacenew, '', '', "script"); $tablespacenew = checkInput($tablespacenew, '', '', "."); 
                    $fsizenew = checkInput($fsizenew , '', '', "script");         $fsizenew = checkInput($fsizenew , '', '', "."); 
                    $fnew = checkInput($fnew, '', '', "script");             $fnew = checkInput($fnew, '', '', "."); 
                    $boardlogonew = checkInput($boardlogonew, '', '', "script"); 
                    $imgdirnew = checkInput($imgdirnew, '', '', "script");         if(FunForum_su($SETTINGS[CustomTheme], 1) == "0"){ $imgdirnew = checkInput($imgdirnew, '', '', "."); }
                    $smdirnew = checkInput($smdirnew, '', '', "script");         if(FunForum_su($SETTINGS[CustomTheme], 2) == "0"){ $smdirnew = checkInput($smdirnew, '', '', "."); }
                    $cattextnew = checkInput($cattextnew, '', '', "script"); $cattextnew = checkInput($cattextnew, '', '', "."); 

                    $db->query("UPDATE ".$tablepre."members_themes SET CustomTheme='$usectnew|$sharectnew', name='$namenew', bgcolor='$bgcolornew', altbg1='$altbg1new', altbg2='$altbg2new', link='$linknew', bordercolor='$bordercolornew', header='$headernew', headertext='$headertextnew', top='$topnew', catcolor='$catcolornew', tabletext='$tabletextnew', text='$textnew', borderwidth='$borderwidthnew', tablewidth='$tablewidthnew', tablespace='$tablespacenew', fontsize='$fsizenew', font='$fnew', boardimg='$boardlogonew', imgdir='$imgdirnew', smdir='$smdirnew', cattext='$cattextnew' WHERE uid='$self[uid]'");
                    $db->query("UPDATE $table_members SET CustomTheme='$usectnew|$sharectnew' WHERE uid='$self[uid]'");
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o14].'</td></tr>';
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }elseif($ctcancel){
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o15].'</td></tr>';
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }elseif($ctother){
                    if(empty($otheruid)) {
                     $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang['ct_o39'].'</td></tr>';
                    }else{
                     $querg = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE (uid='$otheruid' AND (CustomTheme='0|1' OR CustomTheme='1|1'))");
                     $t = $db->fetch_array($querg);
                     if(FunForum_su($SETTINGS[CustomTheme], 3) == "1"){ $t_name = $t[name]; }
                     else{ $t_name = "$self[username]$lang[ct_o31]"; $t_name = addslashes($t_name); }
                     $db->query("UPDATE ".$tablepre."members_themes SET name='$t_name', bgcolor='$t[bgcolor]', altbg1='$t[altbg1]', altbg2='$t[altbg2]', link='$t[link]', bordercolor='$t[bordercolor]', header='$t[header]', headertext='$t[headertext]', top='$t[top]', catcolor='$t[catcolor]', tabletext='$t[tabletext]', text='$t[text]', borderwidth='$t[borderwidth]', tablewidth='$t[tablewidth]', tablespace='$t[tablespace]', fontsize='$t[fontsize]', font='$t[font]', boardimg='$t[boardimg]', imgdir='$t[imgdir]', smdir='$t[smdir]', cattext='$t[cattext]' WHERE uid='$self[uid]'");
                     $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o20].'</td></tr>';
                    }
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }elseif($ctdefault){
                    $querg = $db->query("SELECT * FROM ".$tablepre."members_themes WHERE (themeid='1' AND uid='0')");
                    $t = $db->fetch_array($querg);
                    if(FunForum_su($SETTINGS[CustomTheme], 3) == "1"){ $t_name = $t[name]; }
                    else{ $t_name = "$self[username]$lang[ct_o31]"; $t_name = addslashes($t_name); }
                    $db->query("UPDATE ".$tablepre."members_themes SET name='$t_name', bgcolor='$t[bgcolor]', altbg1='$t[altbg1]', altbg2='$t[altbg2]', link='$t[link]', bordercolor='$t[bordercolor]', header='$t[header]', headertext='$t[headertext]', top='$t[top]', catcolor='$t[catcolor]', tabletext='$t[tabletext]', text='$t[text]', borderwidth='$t[borderwidth]', tablewidth='$t[tablewidth]', tablespace='$t[tablespace]', fontsize='$t[fontsize]', font='$t[font]', boardimg='$t[boardimg]', imgdir='$t[imgdir]', smdir='$t[smdir]', cattext='$t[cattext]' WHERE uid='$self[uid]'");
                    $page .= '<tr bgcolor="'.$altbg2.'" class="tablerow"><td colspan="3" align="center">'.$lang[ct_o18].'</td></tr>';
                    redirect("memcp.php?action=ct", 2, X_REDIRECT_JS);
                }
            }else{
                redirect("memcp.php?action=ct&s=activate", 0);
            }
            $page .= '</form>';
        break;
    }
    $page .= '</table></td></tr></table>';

    eval("\$header = \"".template("header")."\";"); $ltpmnw = "
    
    
    <!-- Custom Themes, by FunForum -->
    
    
    "; $header .= $ltpmnw; echo $header;
    makenav($action);
    $throw = $page; $throw .= $ltpmnw;
    echo stripslashes($throw);
} 
// Load the Default Page
else {
    eval("echo (\"".template('header')."\");");
    eval($lang['evalusercpwelcome']);

    makenav($action);

    // Load Buddy List
    $q = $db->query("SELECT b.buddyname, w.invisible, w.username FROM $table_buddys b LEFT JOIN $table_whosonline w ON (b.buddyname=w.username) WHERE b.username='$xmbuser'");
    $buddys = array();
    $buddys['offline'] = '';
    $buddys['online'] = '';
    if (X_ADMIN) {
        while ($buddy = $db->fetch_array($q)) {
            if (strlen($buddy['username']) > 0) {
                if ($buddy['invisible'] == 1) {
                   $buddystatus = $lang['hidden'];
                } else {
                    $buddystatus = $lang['textonline'];
                }
                eval("\$buddys['online'] .= \"".template("buddylist_buddy_online")."\";");
            } else {
                eval("\$buddys['offline'] .= \"".template("buddylist_buddy_offline")."\";");
            }
        }
    } else {
        while ($buddy = $db->fetch_array($q)) {
            if (strlen($buddy['username']) > 0) {
                if ($buddy['invisible'] == 1) {
                   eval("\$buddys[offline] .= \"".template("buddylist_buddy_offline")."\";");
                   continue;
                } else {
                    $buddystatus = $lang['textonline'];
                }
                eval("\$buddys['online'] .= \"".template("buddylist_buddy_online")."\";");
            } else {
                eval("\$buddys['offline'] .= \"".template("buddylist_buddy_offline")."\";");
            }
        }
    }
	
	  // Member Control Panel Quick Themes Mod Begin
    $quickthemes = '';
    $listquickthemes = '';
    $query = $db->query("SELECT themeid, name FROM $table_themes ORDER BY name ASC");
    while ($qt = $db->fetch_array($query)) {
        if ($theme == $qt['themeid']) {
            $listquickthemes .= "<option value=\"" .$qt['themeid']. "\" selected=\"selected\">" .stripslashes($qt['name']). "</option>\n";
        } else {
            $listquickthemes .= "<option value=\"" .$qt['themeid']. "\">" .stripslashes($qt['name']). "</option>\n";
        }
    }
    eval("\$quickthemes = \"".template("memcp_home_themes")."\";");
    // Member Control Panel Quick Themes Mod Begin

    $query = $db->query("SELECT * FROM $table_members WHERE username='$xmbuser'");
    $member = $db->fetch_array($query);

    if ($member['avatar'] == "") {
        $member['avatar'] = "&nbsp;";
    } else {
        $member['avatar'] = "<img src=\"" .$member['avatar']. "\" border=\"0\" alt=\"$lang[altavatar]\" />";
    }

    if ($member['mood'] != '') {
        $member['mood'] = censor($member['mood']);
        $member['mood'] = postify($member['mood'], 'no', 'no', 'yes', 'no', 'yes', 'no', true, 'yes');
    } else {
        $member['mood'] = '&nbsp;';
    }

    // Signature In Member Control Panel Mod Begin
    $sigblock = '';
    if (!empty($member['sig'])) {
	    $member['sig'] = censor($member['sig']);
	    $member['sig'] = postify($member['sig'], 'no', 'no', 'yes', 'no', 'yes', 'yes', false, 'no', 'no');
	    eval("\$sigblock = \"".template("memcp_home_sig")."\";");
    }
    // Signature In Member Control Panel Mod End

// Make the Page
    $query = $db->query("SELECT * FROM $table_u2u WHERE owner='$xmbuser' AND type='incoming' ORDER BY dateline DESC LIMIT 0, 15");
    $u2unum = $db->num_rows($query);
    $messages = '';

    $tmOffset = ($timeoffset * 3600) + ($addtime * 3600);

    while ($message = $db->fetch_array($query)) {
        $postdate = gmdate("$dateformat",$message['dateline'] + $tmOffset);
        $posttime = gmdate("$timecode",$message['dateline'] + $tmOffset);
        $senton = "" .$postdate. " " .$lang['textat']. " " .$posttime. "";

        if ($message['subject'] == '') {
            $message['subject'] = "&laquo;" .$lang['textnosub']. "&raquo;";
        }

        if ($message['readstatus'] == "yes") {
            $read = $lang['textread'];
        } else {
            $read = $lang['textunread'];
        }

        $message['subject'] = stripslashes(censor($message['subject']));
        eval("\$messages .= \"".template("memcp_home_u2u_row")."\";");
    }

    if ($u2unum == 0) {
        eval("\$messages = \"".template("memcp_home_u2u_none")."\";");
    }

    $query2 = $db->query("SELECT * FROM $table_favorites f, $table_threads t, $table_posts p WHERE f.tid=t.tid AND p.tid=t.tid AND p.subject=t.subject AND f.username='$xmbuser' AND f.type='favorite' ORDER BY t.lastpost DESC LIMIT 0,5");
    $favnum = $db->num_rows($query2);
    $favs = '';

    $tmOffset = ($timeoffset * 3600) + ($addtime * 3600);

    while ($fav = $db->fetch_array($query2)) {
        $query = $db->query("SELECT name, fup, fid FROM $table_forums WHERE fid='$fav[fid]'");
        $forum = $db->fetch_array($query);
        $lastpost = explode("|", $fav['lastpost']);
        $dalast = $lastpost['0'];
        $lastpost['1'] = "<a href=\"member.php?action=viewpro&amp;member=".rawurlencode($lastpost[1])."\">$lastpost[1]</a>";
        $lastreplydate = gmdate($dateformat, $lastpost['0'] + $tmOffset);
        $lastreplytime = gmdate($timecode, $lastpost['0'] + $tmOffset);
        $lastpost = "" .$lang['lastreply1']. " " .$lastreplydate. " " .$lang['textat']. " " .$lastreplytime. " " .$lang['textby']. " " .$lastpost['1']. "";
        $fav['subject'] = stripslashes(censor($fav['subject']));

        if ($fav['icon'] != "") {
            $fav['icon'] = "<img src=\"" .$smdir. "/" .$fav['icon']. "\" />";
        } else {
            $fav['icon'] = "&nbsp;";
        }

        eval("\$favs .= \"".template("memcp_home_favs_row")."\";");
    }

    if ($favnum == 0) {
        eval("\$favs = \"".template("memcp_home_favs_none")."\";");
    }

    eval('echo stripslashes("'.template('memcp_home').'");');
}

end_time();
eval("echo (\"".template('footer')."\");");
?>